# Generated by Django 4.2 on 2023-04-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAPiVista', '0003_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='N_credito',
            field=models.PositiveIntegerField(),
        ),
    ]
