# Generated by Django 4.2 on 2023-04-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAPiVista', '0004_alter_materia_n_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='facultad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appAPiVista.facultad'),
        ),
    ]
