# Generated by Django 4.2 on 2023-04-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAPiVista', '0005_persona_facultad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacion_Materia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appAPiVista.materia')),
                ('id_persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appAPiVista.persona')),
            ],
            options={
                'verbose_name': 'Relacion_Materia',
                'verbose_name_plural': 'Relaciones_Materias',
                'ordering': ['id'],
            },
        ),
    ]
